export const projectDetails = [
  {
    img: "https://framerusercontent.com/images/kfr022WaJ8YJUyZFmdwCB3pXhs.jpg?scale-down-to=1024",
    title: "Aire",
    link: "",
    video: false,
    available: true,
  },
  {
    img: "https://framerusercontent.com/images/QVKFKT3dyGxloXfzzpurVKNMM6M.jpg?scale-down-to=1024",
    title: "Correlated",
    link: "",
    video: false,
    available: true,
  },
  {
    img: "https://framerusercontent.com/images/AX9PukosNfGVcfXw3YapiYpl9g.jpg?scale-down-to=1024",
    title: "Channel 5",
    link: "",
    video: false,
    available: true,
  },
  {
    img: "https://framerusercontent.com/images/BAXywubxN8sAhfJg3AgGgFI.jpg?scale-down-to=1024",
    title: "Ronald Abram",
    link: "",
    video: false,
    available: true,
  },
  {
    img: "https://framerusercontent.com/modules/assets/XuzMZ3Z1QQHKltPqRjzGnsWs27M~Jq48dGctHPeHtnn90xE_Aem-3HQJB_aNVwfu2fao5Ok.mp4",
    title: "Propeller",
    link: "",
    video: true,
    available: true,
  },
  {
    img: "	https://framerusercontent.com/images/3WALBX7nnuG7p85CLjlVmWPDHw.jpg?scale-down-to=1024",
    title: "Schuh",
    link: "",
    video: false,
    available: true,
  },
  {
    img: "https://framerusercontent.com/images/e3moUZXfgtjYQY4ILakIMaz4n7s.jpg?scale-down-to=512",
    title: "Paperstreet",
    link: "",
    video: false,
    available: true,
  },
  {
    img: "https://framerusercontent.com/modules/assets/SGjFvgcbK7s4yKh0xwuNjriMNII~5SCIlrVv6SNR5PFMjsMv3qAIi3sYsG2gjdlB0qM-tng.mp4",
    title: "OH.SUPPLY",
    link: "",
    video: true,
    available: true,
  },
  {
    img: "https://framerusercontent.com/images/aH1eUgCIIIrbJF7TUlaKAehoI.jpg?scale-down-to=1024",
    title: "Monokel Eyewear",
    link: "",
    video: false,
    available: true,
  },
  {
    img: "https://framerusercontent.com/images/UbS7rWmAwWxjtwM7oaWwRuGo.jpg?scale-down-to=1024",
    title: "Lawtrades",
    link: "",
    video: false,
    available: false,
  },
  {
    img: "https://framerusercontent.com/images/hQVBeiDNGU2TfeDJALuhawlcto.jpg?scale-down-to=1024",
    title: "Baselworld",
    link: "",
    video: false,
    available: false,
  },
  {
    img: "https://framerusercontent.com/modules/assets/NieGBlxBdgpz9QCHV5Aj89rWjVg~DPEeC0jYyBwx9c865cOkUi-KzBM-3ukyhpgtPhvYo_U.mp4",
    title: "NYCB",
    link: "https://oh.studio/projects/nycb",
    video: true,
    available: true,
  },
];
